from dotenv import load_dotenv
from anthropic import Anthropic

load_dotenv()

client = Anthropic()
MODEL = "claude-haiku-4-5"


def add_user_message(messages: list, content: str) -> None:
    messages.append({"role": "user", "content": content})

# Initializing the messages list
messages = []
add_user_message(messages, "Write a 1 sentence description of a fake database")

# Using the text_stream property of the stream object to print the response as it is generated by the model
# with client.messages.stream(
#     model=MODEL,
#     max_tokens=1000,
#     messages=messages
# ) as stream:
#     for text in stream.text_stream:
#         print(text, end="")


# Getting the Complete Message
with client.messages.stream(
    model=MODEL,
    max_tokens=1000,
    messages=messages
) as stream:
    for text in stream.text_stream:
        # Send each chunk to your client
        pass
    
    # Get the complete message for database storage
    final_message = stream.get_final_message()